---
- name: Create Python virtual environment and install dependencies
  hosts: django_servers
  become: true
  gather_facts: true
  tasks:
    - name: Install TODO Reqs
      ansible.builtin.pip:
        virtualenv: /home/ec2-user/django/todo-list-master/venv
        requirements: /home/ec2-user/django/todo-list-master/requirements.txt

    - name: Copy env file
      ansible.builtin.copy:
        src: /home/ec2-user/.env
        dest: /home/ec2-user/django/todo-list-master/.env
        owner: ec2-user
        group: ec2-user
        mode: '0644'

- name: Gunicorn Service Setup and Handler
  hosts: django_servers
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Copy Gunicorn systemd service file
      template:
        src: /home/ec2-user/todo.service
        dest: /etc/systemd/system/todolist.service
      register: gunicorn_service

    - name: Enable and start Gunicorn service
      systemd:
        name: todolist
        state: started
        enabled: yes
      when: gunicorn_service.changed
      notify:
        - Restart Gunicorn

    - name: Restart Gunicorn
      systemd:
        name: todolist
        state: restarted
      when: gunicorn_service.changed

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: todolist
        state: restarted

- name: Configure Nginx as a reverse proxy
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Configure Nginx
      template:
        src: /home/ec2-user/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted